### PR TITLE
Use flock instead of temporary files to avoid races/purge on ENOSPC/fsync time

### PR DESCRIPTION
**Pull request by azat**
- races: two parallel `autojump --add` can lead to database purging
  (overwriting by one of tmp files)
- ENOSPC: will leave autojump.txt empty, because no free space available
- fsync: can take a while

All of this can be fixed with fsync(2).

P.S. maybe there are some issues on win32, and/or not all places didn't guard by flock.

### CODE REVIEW

**Comment by azat** [comment]
Hm, but this can hurt with unproper shutdown, maybe leave tmp files but overwriting main db under flock?

**Comment by wting** [comment]
Ugh, sorry I lost this PR in the noise. Linking #391.

**Comment by trou** [comment]
FWIW I've run autojump with this PR and it didn't fully fix the problem, it seemed to be less frequent but no hard number.

**Comment by azat** [comment]
I guess that problem can be with ENOSPC

**Comment by azat** [comment]
I got zeros ('\0') sometimes, and it fails to parse `autojump.txt`

**Pull request closed without merging**
